### PR TITLE
Update class method in nodes.pyi stub

### PR DESCRIPTION
**Pull request by Huy-Ngo**
Add stubs for new method in class `Node`.

### CODE REVIEW

**Comment by McSinyx** [comment]
Fun fact: this was added to 0.21 but never made it to this Git repo.

**Comment by Huy-Ngo** [comment]
Oh right, I didn't notice 0.21 isn't here...

**Comment by tk0miya** [comment]
OMG... I also missed the code for 0.21...

**Comment by tk0miya** [comment]
Thank you for your contribution!

**Pull request merged**
